=== skoba/mml5/schema/mml_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Container",
    "description": "Container class of all items for MML",
    "type": "object",
    "properties": {
	"doc_id": {
	    "description": "document identifier, usually uuid",
	    "type": "string"
	},
	"concept_id": {
	    "description": "Concept identifier for each instances.",
	    "type": "string"
	},
	"created": {
	    "description": "The time when the instance created at.",
	    "type": "string",
	    "format": "date-time"
	},
	"security": {
	    "type": "object",
	    "properties": {
		"access_rights": {
		    "type": "array",
		    "items": {
			"type": "object",
			"properties": {
			    "allow": {
				"type": "string"
			    },
			    "disallow": {
				"type": "string"
			    }
			}
		    }
		},
		"use": {
		    "type": "string"
		}
	    }
	},
	"context": {
	    "type": "object",
	    "properties": {
		"publisher": "string"
	    }
	},
	"content": {
	    "type": "array",
	    "items": {
		"type": "object",
		"properties": {
		    "concept_id": {
			"type": "string"
		    },
		    "nodes": {
			"type": "array",
			"items": {
			    "type": "object",
			    "properties": {
				"name": {
				    "type": "string"
				},
				"value": {
				    "type": "string"
				}
			    }
			}
		    }
		}
	    }
	}
    },
    "required": ["doc_id", "concept_id", "created", "context", "content"]
}

=== skoba/mml5/samples/mml_sample.json
{
    "doc_id": "0123-4567-801",
    "concept_id": "MML Sample",
    "created": "2017-05-28T15:00:00+09:00",
    "security": {
	"access_rights": [
	    { "disallow": "Kamogawa University"},
	    { "allow": "all" }
	],
	"use": "ANY"
    },
    "context": {
	"pulisher": "EHR Lab"
    },
    "content": [
	{ "concept_id": "MML Progress Course" }
    ]
}
